on: [push, pull_request]

jobs:
  splitByBuildTypesTrue:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - { name: "VISUAL", version: "14", buildType: "Debug"   }
        - { name: "VISUAL", version: "14", buildType: "Release" }
        - { name: "VISUAL", version: "15", buildType: "Debug"   }
        - { name: "VISUAL", version: "15", buildType: "Release" }
        - { name: "VISUAL", version: "16", buildType: "Debug"   }
        - { name: "VISUAL", version: "16", buildType: "Release" }
    name: ${{ matrix.compiler.name }} ${{ matrix.compiler.version }} ${{ matrix.compiler.buildType }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.2'
      - name: Install Conan
        run: |
          pip install bincrafters_package_tools
          conan user
      - name: Run
        env:
          CONAN_USE_DOCKER: 1
          CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
          CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
          CONAN_BUILD_TYPES: ${{ matrix.compiler.buildType }}
          CONAN_SYSREQUIRES_MODE: enabled
        run: |
          SET CONAN_${{ matrix.compiler.name }}_VERSIONS="${{ matrix.compiler.version }}"
          python build.py
