on: [push, pull_request]

jobs:
  splitByBuildTypesTrue:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-2016, name: "VISUAL", version: "15", versionForConan: "15.0", buildType: "Debug"   }
          - { os: windows-2016, name: "VISUAL", version: "15", versionForConan: "15.0", buildType: "Release" }
          - { os: windows-2019, name: "VISUAL", version: "16", versionForConan: "16.0", buildType: "Debug"   }
          - { os: windows-2019, name: "VISUAL", version: "16", versionForConan: "16.0", buildType: "Release" }
    name: ${{ matrix.config.name }} ${{ matrix.config.version }} ${{ matrix.config.buildType }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.2'
      - name: Install Conan
        run: |
          pip install bincrafters_package_tools
          conan user
      - name: Run
        env:
          CONAN_BUILD_TYPES: ${{ matrix.config.buildType }}
        run: |
          SET CONAN_${{ matrix.config.name }}_VERSIONS="${{ matrix.config.versionForConan }}"
          python build.py
